name: CI

on:
  pull_request:
    branches:
      - master
      - develop

  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [ '12', '14']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: npm install, lint and test
        run: |
          npm install
          npm run lint
          npm test

  collect_coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run tests
        run: |
          npm install
          npm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.5.0

      - name: Run Stryker
        run: npm run test.mutation
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
